### ISSUE TITLE
enhancement: type definitions should include type predicate

### ISSUE THREAD

**Issue by reverie** [jshttp/http-assert#10]
It would be nice if `assert` at least annotated that the value is not `undefined`.

https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates

**Comment by Gerhut** [comment]
Consider https://github.com/Gerhut/ts-http-assert

**Comment by dougwilson** [comment]
Type definitions are maintained here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/http-assert
