### ISSUE TITLE
May I response a json?

### ISSUE THREAD

**Issue by libook** [jshttp/http-assert#7]
I can use http-assert in this way:

``` javascript
this.assert(this.request.body.urlId, 400, 'There should be an url ID.');
```

But in many times, I want to response a json like this:

``` javascript
this.assert(this.request.body.urlId, 400, {"message":"There should be an url ID.","anotherObject":{}});
```

This does not work probably.
So will you support this method?

**Comment by sorahn** [comment]
@libook 
This works: this.assert(param, 400, JSON.stringify({ msg: "It died" }))

**Comment by jonathanong** [comment]
what is the purpose of this? you can just have your error handle json stringify the error however you'd like

**Comment by libook** [comment]
Well, http-assert just respond to client when there was an 'false'.
And it only respond the error message in body.
What if the client needs more information form body.
I think responding a JSON could be a perfect way.

**Comment by dougwilson** [comment]
I'm sorry, I don't understand what the ask even is here, after reading this. All this module does is throw an `Error` object; it doesn't do any serialization. Perhaps a PR may help communicate the idea across in code form.
